apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "newegg-nginx.full_name" . }}
  labels: 
    {{- include "newegg-nginx.release_labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "newegg-nginx.release_labels" . | indent 8 }}
    spec:
      containers:
        - name: hello-world
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
