apiVersion: v1
kind: Service
metadata:
  name: {{ template "newegg-nginx.full_name" . }}
  labels: 
    {{- include "newegg-nginx.release_labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ template "newegg-nginx.full_name" . }}
